// Generated by Tools/v41_flash/engram_constants.py. Do not edit by hand.
//
// Regenerate with:
//     python3 Tools/v41_flash/engram_constants.py
// and check for staleness with `--check`. `Tools/v41_flash/test_engram_constants.py`
// re-derives every number here from DeepSeek's own `inference/engram.py`, and
// `DeepSeekV41EngramConstantsTests` holds these literals to the JSON copy in
// `Tests/Fixtures/deepseek-v41/engram-constants.json`.

/// The fixed hash geometry of DeepSeek V4.1 Flash's Engram conditional memory.
///
/// Every number is an output of the reference implementation, not a Minirun
/// choice. The multipliers come from a numpy PCG64 stream seeded per layer and
/// the bucket moduli from a prime search whose `seen` set spans both layers, so
/// neither can be recomputed here without re-implementing numpy and a sieve.
/// They are literals for the same reason a tokenizer's merge table is: the
/// generator that produced them is the only thing that may.
///
/// Provenance: deepseek-ai/DeepSeek-V4.1-Flash @ df42c109f1defefcbfcedbe7d905718a12266e40
///   `inference/config.json` 2e84f45cf1dac8c7fcbb200e96667d4b913275690668ed496f24c7747207a809
///   `inference/engram.py` 11f35ecbead8150c35aa002b3d180ef290b05a25afe883a11884f94d476d3897
///   `inference/model.py` 4e9ae23620edc8028ccc5d5fef552ab7fdc7dcd6f79608754fe9f67644056f65
public enum DeepSeekV41EngramConstants {
    /// The blocks that carry an Engram module, in the order their tables are
    /// declared. A hash row index is only meaningful against its own layer.
    public static let layerIDs: [Int] = [1, 14]
    /// N-grams of order 2...maxNgramSize are hashed; order 1 is not a lookup.
    public static let maxNgramSize = 4
    /// Hash heads per n-gram order.
    public static let headCount = 8
    /// Values in one table row.
    public static let headDimension = 256
    /// Values one E8M0 scale covers, so a row's eight scale bytes cover its
    /// 256 values. Also the dense FP8 block size, in both directions.
    public static let scaleGroupSize = 32
    /// `(maxNgramSize - 1) * headCount` row lookups per token per layer.
    public static let hashColumnCount = 24
    /// Where each `(order, head)` prime search begins, before `- 1`.
    public static let primeSearchStart = 16_000_000
    /// Distinct classes the tokenizer's compressed map collapses onto. Every
    /// multiplier above is bounded by this, so a map that produced a different
    /// count would silently rehash the whole table.
    public static let compressedVocabularySize = 99_092
    /// The *tokenizer* id whose compressed id fills n-gram slots with no
    /// history. Compress it through the token map before hashing with it.
    public static let padTokenID = 2
    /// Rows in each layer's table; equal to that layer's primes summed.
    public static let rowCounts: [Int] = [384_006_168, 384_016_682]

    /// `[layer][lookback]`, odd, and bounded so `compressedID * multiplier`
    /// cannot overflow Int64.
    public static let multipliers: [[Int64]] = [
        [76_632_096_046_245, 4_839_876_093_313, 35_959_672_319_349, 73_987_337_458_391],
        [67_716_810_739_261, 51_510_806_800_915, 30_921_347_202_721, 82_619_226_485_591],
    ]

    /// `[layer][order - 2][head]`, the bucket modulus of each hash column.
    public static let primes: [[[Int]]] = [
        [
            [
                16_000_057, 16_000_079, 16_000_081, 16_000_097,
                16_000_121, 16_000_129, 16_000_133, 16_000_183,
            ],
            [
                16_000_189, 16_000_207, 16_000_211, 16_000_253,
                16_000_277, 16_000_289, 16_000_307, 16_000_321,
            ],
            [
                16_000_339, 16_000_381, 16_000_393, 16_000_399,
                16_000_403, 16_000_409, 16_000_447, 16_000_463,
            ],
        ],
        [
            [
                16_000_477, 16_000_487, 16_000_499, 16_000_507,
                16_000_511, 16_000_573, 16_000_609, 16_000_627,
            ],
            [
                16_000_667, 16_000_669, 16_000_693, 16_000_697,
                16_000_711, 16_000_729, 16_000_759, 16_000_769,
            ],
            [
                16_000_781, 16_000_799, 16_000_813, 16_000_819,
                16_000_841, 16_000_877, 16_000_879, 16_000_889,
            ],
        ],
    ]

    /// `[layer][column]`, the exclusive prefix sum of that layer's primes
    /// flattened in draw order. A column's row index is `hash % prime + offset`.
    public static let bucketOffsets: [[Int]] = [
        [
            0, 16_000_057, 32_000_136, 48_000_217,
            64_000_314, 80_000_435, 96_000_564, 112_000_697,
            128_000_880, 144_001_069, 160_001_276, 176_001_487,
            192_001_740, 208_002_017, 224_002_306, 240_002_613,
            256_002_934, 272_003_273, 288_003_654, 304_004_047,
            320_004_446, 336_004_849, 352_005_258, 368_005_705,
        ],
        [
            0, 16_000_477, 32_000_964, 48_001_463,
            64_001_970, 80_002_481, 96_003_054, 112_003_663,
            128_004_290, 144_004_957, 160_005_626, 176_006_319,
            192_007_016, 208_007_727, 224_008_456, 240_009_215,
            256_009_984, 272_010_765, 288_011_564, 304_012_377,
            320_013_196, 336_014_037, 352_014_914, 368_015_793,
        ],
    ]
}
