import Foundation
import PackagePlugin

/// Writes the git revision of the package checkout into a generated Swift file
/// before every build, so that a benchmark result can name the code that
/// produced it (spec 17.4) without the binary shelling out to git at run time.
///
/// The generated script never fails the build. If git is missing, the checkout
/// is not a repository, or the plugin sandbox denies the call, the revision
/// degrades to "unknown" — an honest missing value is better than a broken
/// build, and better than a stale value committed to the repository.
@main
struct EmbedGitRevision: BuildToolPlugin {
    func createBuildCommands(context: PluginContext, target: Target) throws -> [Command] {
        let outputDirectory = context.pluginWorkDirectory
        let outputFile = outputDirectory.appending("GeneratedBuildRevision.swift")
        let packageDirectory = context.package.directory.string

        let script = """
        set -u
        out=\(shellQuoted(outputFile.string))
        pkg=\(shellQuoted(packageDirectory))
        rev=$(git -C "$pkg" rev-parse --short=12 HEAD 2>/dev/null) || rev=""
        if [ -n "$rev" ]; then
            if [ -n "$(git -C "$pkg" status --porcelain 2>/dev/null)" ]; then
                rev="$rev-dirty"
            fi
        else
            rev="unknown"
        fi
        new="// Generated by the EmbedGitRevision plugin. Do not edit, do not commit.
        let minirunEmbeddedGitRevision = \\"$rev\\"
        "
        # Only rewrite when the value changed, so an unchanged revision does not
        # force a rebuild of the whole target on every invocation.
        if [ ! -f "$out" ] || [ "$(cat "$out")" != "$new" ]; then
            printf '%s' "$new" > "$out"
        fi
        """

        return [
            .prebuildCommand(
                displayName: "Embed git revision for \(target.name)",
                executable: Path("/bin/sh"),
                arguments: ["-c", script],
                outputFilesDirectory: outputDirectory
            )
        ]
    }
}

private func shellQuoted(_ value: String) -> String {
    "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
}
